name: openscad
version: 0.4.0

github: ejconlon/haskell-openscad
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: OpenSCAD code gen
description: Please see the README on GitHub at <https://github.com/ejconlon/haskell-openscad#readme>
tested-with: GHC == 9.6.6

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5

library:
  source-dirs: src

executables:
  openscad-exe:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openscad

tests:
  openscad-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openscad
    - tasty
    - tasty-hunit
